---
name: runtests
run-name: Run test suite for trac-github
on: [pull_request]
jobs:
  runtests-py2:
    runs-on: ubuntu-20.04
    container:
      image: python:2.7.18-buster

    steps:
      - uses: actions/checkout@v5
      - run: pip install nox-py2
      - run: git config --global user.name runtest
      - run: git config --global user.email runtest@localhost
      - run: |
          which -a nox && stat "$(which nox)"
          nox --non-interactive --error-on-missing-interpreter \
            --session runtests -- --git-default-branch=master
